#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';
require_once __DIR__ . '/app/Core/Console/Info.php';

use Symfony\Component\Console\Application;
use App\Core\Console\Info;

$console = new Application();

$console->add(new Info());
$console->run();